{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bolometer.fullname" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bolometer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "bolometer.selectorLabels" . | nindent 4 }}
{{- end }}
