apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ../rbac/service_account.yaml
- ../rbac/role.yaml
- ../rbac/role_binding.yaml
- ../crd/bolometer.io_profilingconfigs.yaml

