apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bolometer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bolometer-role
subjects:
- kind: ServiceAccount
  name: bolometer
  namespace: bolometer-system

