apiVersion: v1
kind: ServiceAccount
metadata:
  name: bolometer
  namespace: bolometer-system
  annotations:
    # Add IRSA annotation for AWS
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/bolometer-role

