apiVersion: v2
name: bolometer
description: Measuring the heat of your applications - Kubernetes operator for intelligent Go profiling
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - profiling
  - pprof
  - golang
  - go
  - performance
  - monitoring
  - observability
  - bolometer
  - threshold
maintainers:
  - name: Akash Singh
    email: akashsinghkld+bolometer@gmail.com
home: https://github.com/a-kash-singh/bolometer
sources:
  - https://github.com/a-kash-singh/bolometer
